### ISSUE TITLE
License information in the certificate summary is incorrect

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1001]
If a dataset is licensed under a different version of a license but has the same abbreviation as a common license (such as `CC-BY`) then `ResponseSet#data_licence_determined_from_responses` is using `Odlifier` to lookup the license by `license_id` and is finding the most recent standard version of the license as decided by http://licenses.opendefinition.org/ list, for example `CC-BY-4.0`.

This seems to be caused by the questionnaire only having an approved list of licenses and the importer then trying to convert the answers to fit this format.

**Comment by sumikasan** [comment]
I think this is closed now fixed #997
