### ISSUE TITLE
Draft certificates now missing

### ISSUE THREAD

**Issue by BenPWhite** [theodi/open-data-certificate#1003]
I was working on my certificating my organisations Open Datasets using the ODI Data Certificate beta service, and had a number of draft certificates saved, none of the draft certificates are now present.  I last successfully accessed them in September 2014.  Not sure what has happened but would prefer to retrieve the draft certificates rather than keying all the information in again

**Comment by pkqk** [comment]
resolved via email.

Ownership was changed after the data.gov.uk import.
