### ISSUE TITLE
Update source Italian translation file

### ISSUE THREAD

**Issue by JeniT** [theodi/open-data-certificate#1006]
#1004 hasn't updated the files that we use as the source of the questionnaire here:

  https://github.com/theodi/open-data-certificate/blob/master/prototype/translations/certificate.it.xml

and here:

  https://github.com/theodi/open-data-certificate/blob/master/prototype/jurisdictions/certificate.IT.xml

We should make sure these are in sync with the new text, because these form the basis for any structural changes needed in the question flow.

**Comment by pkqk** [comment]
Are the .xml files authoritative? If that's the case maybe we shouldn't have the .yml files be in source control and generate them on deploy.

**Comment by pkqk** [comment]
perhaps we also need a guide on how to contribute to translations?

**Comment by JeniT** [comment]
Agreed, having them automatically generated would be great. It requires XSLT processing. @pezholio should be able to explain, otherwise I can.

It's very rare for translations to be supplied by github savvy people: we usually expect these changes will have to be applied by hand based on emailed descriptions of changes. (There is a guide for initial translation, based on CSV files.)

**Comment by pkqk** [comment]
This was unpicked and the translation changing code is a bit easier to run now.

Though submissions where only the `.yml` or `.rb` is changed will still need manually conversion :cry:
