### ISSUE TITLE
Looking up licences on opendefintion.org is convoluted.

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1007]
Changes and mysterious bugs have caused several failures lately.

Though from the certificate form there is only a pre-approved list of licenses to choose from so we don't need to look those up. We should be storing them by URL or something more reliable than a string title.

The lookup may still be useful for auto generated certificates but needs to be cleaned up from the 3 http request dance through a gem that it currently is.

**Comment by pezholio** [comment]
:+1: for this
