### ISSUE TITLE
Published certificate disappeared from dashboard

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#1024]
I'm helping a user with some revisions to their certificate, but they've hit "publish" and its no longer appearing on their dashboard.

The certificate is:

https://certificates.theodi.org/datasets/1709/certificate

I've seen a screenshot and their dashboard now only lists a single draft certificate, the published one is no longer there.

Any help appreciated -- looks like this will be our first Expert certificate once its tweaked so keen to get it published!

**Comment by pkqk** [comment]
Hi @ldodds,

Which user is this the dashboard from, the certificate changed ownership on the 16th Jan to `r********@manchester.ac.uk` and is waiting to be accepted back by the account it was transferred from, `c****@essex.ac.uk`.

**Comment by Floppy** [comment]
I approve the starring out of email addresses here, but now my brain is just filling in swear words.

**Comment by ldodds** [comment]
Missed this update sorry @pkqk. I cancelled the transfer and redid it and thats done the trick.
