### ISSUE TITLE
Stats on dashboard and status page don't match up

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1026]
Numbers are slightly different, possibly related to published count from `response_sets` and `certificates`

**Comment by pkqk** [comment]
The sum of [raw, pilot, standard, exemplar] certificate counts is slightly less (starting in november by 1, and then 2 in december) than the total count in `/status.csv&type=published`

**Comment by pkqk** [comment]
@sumikasan and @pkqk to have a timeboxed discussion on how to count things.

**Comment by sumikasan** [comment]
https://github.com/theodi/open-data-certificate/issues/1092

**Comment by shevski** [comment]
@Floppy hey, do you want to look into which page calculates the stats wrong? Pls reopen in odi shared if so.
