### ISSUE TITLE
Incorrectly certifying - data.gov.uk automatic certification

### ISSUE THREAD

**Issue by statshero** [theodi/open-data-certificate#1030]
I have doubts whether this dataset fulfils the 'raw' requirements alone because of the strange file format.

http://data.gov.uk/dataset/hazardous-waste-interrogator

**Comment by pkqk** [comment]
Looks like this is a bug from the automatically imported datasets, it shouldn't pass for other reasons too as it's missing licence information.

**Comment by pkqk** [comment]
Currently the questionnaire doesn't require the data format to be machine readable to get a raw level certificate. Pilot is the minimum level that requires machine readable data.

This is based on my reading of the questionnaire.en.xml file, is this correct @JeniT?
