### ISSUE TITLE
Localisation - download certificate questionnaire into csv

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#1034]
The version we have at the moment is incorrect. Need a new CSV output so we can supply it to get it localised / translated.

**Comment by pkqk** [comment]
There are several things that need to be done.

  - [ ] For jurisdictions where the questionnaire differs from `UK` we need to generate separate `Legal` sheet.
  - [ ] Need to do an audit of all strings and make sure they are translated and exported to the `Main` sheet
  - [ ] Check that error messages etc are also translated
  - [ ] Check that dynamic messages work with the grammar of the language.

**Comment by pkqk** [comment]
I also think we should change the current translate script so instead of relying on position index paths (`/1/1/2/1/4` i.e 4th child of 1st child of...) and export a new translation source csv using the #id of each question.

So an example csv could be
```
//question[@id="publisherRights"]/label,Do you have the rights to publish this data as open data?
//question[@id="publisherRights"]//option[@value="yes"]/label,yes, you have the rights to publish this data as open data
//question[@id="publisherRights"]//option[@value="yes"]/requirement,You should have a <strong>clear legal right to publish this data</strong>.
```

This means restructuring or reordering of the questionnaire would not break the translation spreadsheet

**Comment by JeniT** [comment]
@pkqk the difficulty with that pattern is in interpretation: there is no 'eval' in XSLT/XPath, so generating the translated XML will be a lot harder  than it is currently. All possible (with sufficient coding time), but not trivial. Unless perhaps you were thinking of applying the translation through some method other than XSLT (eg a Ruby script).

**Comment by pkqk** [comment]
oh, am I misunderstanding how auto-translate currently works, is `/1/2/1/1` etc not being used as a selector?

**Comment by pkqk** [comment]
ah, is it building up the path as it traverses the document and then comparing that with the csv?

**Comment by JeniT** [comment]
Something like that, yes. IIRC, it creates a lookup from the CSV then builds up the path as it traverses the XML and picks out the relevant part. As I say, it's completely possible to parse other predictable selectors to do something similar, but it will require a change to the code. And if you were going that route there's no requirement to use something that looks like an XPath for those selectors --- you could just use something like `publisherRights.label`, `publisherRights.options[2].yes` or whatever makes them understandable.

(btw I don't mind hacking the XSLT to make this work, just wanted to make sure you were aware of the implications)
