### ISSUE TITLE
Keeping derived answers up to date from data portals (such as data.gov.uk)

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1036]
So far certificates that have been automatically awarded have been based off of batch imports run manually and have not been updated with changed answers or added to as new datasets are added to `data.gov.uk`

We have a few options to choose from in how we approach this
1. The ODI runs a regular collection process as part of `certificates` site.
2. DGU runs a regular batch process that uploads references to changed or added datasets.
3. DGU sends a message (webhook/callback etc) when a dataset is updated to `certificates` triggering an update of that certificate.

The downside of the background processes like in options 1 and 2 is that it's kept away from the publisher's view and as @sumikasan has said, the goal is to get publishers aware of good practices in data publishing. So having the certificate process be more visible upon submission may be a nice to have.

A benefit to option 1 is that it is a central process responsible for all updates that we can monitor and improve but it could be a waste of resources and a burden on portals if it has to make polling requests all the time. Once it is checking many portals it may take quite a lot of time to do the rounds also.

Option 2 has the benefit that data.gov.uk can only send what has changed at intervals that suit them but without monitoring the process could stop and we wouldn't necessarily know.

Option 3 might be architecturally more complex since it involves messages between both web servers.

A possible design would be:
1. publisher submits dataset
2. DGU sends a request to ODC giving the url of the dataset, ODC responds back with a job ID.
3. DGU mentions that a certificate is being issued or re-checked to the publisher
4. ODC fetches the changed data and creates or updates a certificate.
5. ODC sends a message back to DGU with the job ID with the outcome and certificate url or data so that DGU can update any references.

**Comment by JeniT** [comment]
I like a combination of options 1 and 3: in the initial phase of integration with a portal we will need to poll (eg on a daily basis) for updates, but when the portal is properly integrated then they can ping us to perform updates for particular certificates, giving a better experience for their users. The integration is fairly lightweight for the portal, because they just have to do the pinging rather than working out exactly what to send via the API to update the certificate.

In a daily process that we run over supported portals we could check whether there have been pings from that portal during the last 24 hours, and not poll it if there have been. This would get around the potential problem of the portal removing the integration from their side and us not knowing.

**Comment by pkqk** [comment]
@sumikasan if we add reporting to this feature, such as how many certificates failed for certain questions then we can use it as the sales/participation tool you mentioned.

So if we set it up to import everything from a portal or source it could certify everything but leave them in draft state.
  - Report how many reach each level
  - Report which questions we are having trouble answering
    - ability to provide default answers
    - instructions on how to add that to portal
  - Then the ability to re-run the import to catch updates.
  - Rinse and repeat
  - A button that publishes all of them at once.

**Comment by Stephen-Gates** [comment]
@pkqk you've got my vote on that suggestion Adam

**Comment by sumikasan** [comment]
I have now split this story up - reporting story is here:
https://github.com/theodi/open-data-certificate/issues/1119

**Comment by sumikasan** [comment]
@pezholio - this is what we need to work on after you close the #1178.

**Comment by pezholio** [comment]
:+1:
