### ISSUE TITLE
Publish CZ translated questionnaire

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#1046]
Tasks are:
- [x] Import translation from https://docs.google.com/a/theodi.org/spreadsheets/d/1YuzGwBH2mSTJ1FoXxwe-JqGe1zx1yi72em9TX03sfno/edit
- [x] Staging for testing
- [ ] UAT
- [ ] Deploy to live site

**Comment by Floppy** [comment]
Where is the content for this? Is #1029 a prerequisite?

**Comment by Floppy** [comment]
Something is broken somewhere. In the translation, the keys should be unique, but we have repeated keys across the two sheets, Legal and Main. The keys repeated are:

```
/1/5/2
/1/5/3
/1/6/2
/1/6/3
/1/6/4/2
/1/6/4/3
/1/6/4/6/2/3
/1/6/4/6/2/5
/1/6/4/6/2/@display
/1/6/5/10/2/3
/1/6/5/10/2/@display
/1/6/5/12/2/3
/1/6/5/12/2/4/1/3
/1/6/5/12/2/4/1/@display
/1/6/5/12/2/4/2/3
/1/6/5/12/2/4/2/4
/1/6/5/12/2/4/2/@display
/1/6/5/12/2/4/3/3
/1/6/5/12/2/4/3/4
/1/6/5/12/2/4/3/@display
/1/6/5/12/2/@display
/1/6/5/2
/1/6/5/3
/1/6/5/4/3
/1/6/5/4/5
/1/6/5/4/6
/1/6/5/4/@display
/1/6/5/5/3
/1/6/5/5/5
/1/6/5/5/@display
/1/6/5/6/3/2/3
/1/6/5/7/2/3
/1/6/5/7/2/@display
/1/6/5/9/2/3
/1/6/5/9/2/@display
/1/6/6/2
/1/6/6/3
/1/6/6/4/3
/1/6/6/4/@display
```

**Comment by Floppy** [comment]
Steps to generate translation file:
1. Download output as TSV with the IDs and the translations.
2. Replace tabs with colons and create temp text file: `cat ~/Downloads/certificate.CZ\ -\ Output.tsv | sed "s/        /: /g" > translations/temp/certificate.cz.txt`
3. Change auto-translate.xsl line 10 to refer to the right language text file
4. Run through saxon `saxon -s:translations/certificate.en.xml -o:translations/temp/certificate.cz.xml -xsl:auto-translate.xsl`

**Comment by pkqk** [comment]
@Floppy I made some helpers to make running the translation process easier.
https://github.com/theodi/open-data-certificate/blob/master/prototype/HOWTO.md

**Comment by sumikasan** [comment]
@pkqk - is this now closed?

**Comment by pkqk** [comment]
@sumikasan yes
