### ISSUE TITLE
Better localization support

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1065]
I am the guy in charge of the Czech questionnaire translation. I just got to reviewing the translation as per #1046 and I am scratching my head over the whole localization process. I am mostly concerned about two things: (1) translator tooling support and (2) translation updates.

The translator tooling support is currently sup-optimal, since all a translator gets is a non-standard spreadsheet that doesn’t supply much translation context and can’t be edited using existing translation tools such as [Transifex](https://www.transifex.com). The second issue is what will happen once the official English translation changes. Currently I’d have no idea if there are untranslated strings or strings that have changed since the last translation.

I have tried to understand the current process. If I get it correctly, you have the English questionnaire in an XML file that’s transformed with XSLT to whatever else is needed. The issue is how to translate this XML file. So far you have solved the problem with a custom script that outputs XPath (?) expressions along with the translatable strings. The XPath expressions are then used to merge the translated strings back to the original document. Is that right?

I haven’t got much experience in translating structured data, but I think it would be better to replace the custom XPath solution with a standard localization interchange format. I have researched the options and found the [XLIFF](https://en.wikipedia.org/wiki/XLIFF) format that seems to be fit for this purpose. What’s better, there’s already an existing solution for transforming XML documents to XLIFF for translation and back, see the [xliffRoundTrip](http://xliffroundtrip.sourceforge.net) project and [this tutorial](http://ao2.it/en/blog/2009/09/09/translating-xml-documents-xliff).

The xliffRoundTrip project is mostly just two XSL templates to convert XML to XLIFF and back. I have tried the conversion, it seems to work fine. After converting the questionnaire to XLIFF, I have succeeded in importing the strings into Transifex:

![Czech translation in Transifex](https://cloud.githubusercontent.com/assets/95329/6845508/be91437a-d3b5-11e4-8c0e-55e3c626ec9b.png)

After translating some strings, I have tried to export the XLIFF and convert it back to XML, seems to work just fine – I got the localized questionnaire back with all the markup seemingly intact.

I’m not sure what would happen when the English source changes in this case. Transifex says the context for a translation string is something like `questionnaire:English (en):plaintext:label-7`, which doesn’t look very stable (but is probably no worse than XPath). In the least Transifex can supply matching translations from the translation memory.

Now, this is a much better workflow for a translator. The whole process can be automated so that Transifex knows about new untranslated strings and you can even get the translated strings back through an API. I suggest that we test-drive the process on the Czech localization and if everything works, we could make this the official translation process for the ODC? :raising_hand: 

(Transifex is free for open source projects, but once we have the questionnaire in XLIFF, the translation can also be done in any other translation tool that supports XLIFF.)

**Comment by zoul** [comment]
I just did a roundtrip with a part of the questionnaire (English XML → English XLIFF → Transifex → Czech XLIFF → Czech XML). The result: XML comments are preserved (good), attribute order is not preserved (acceptable), attribute values (like `placeholder`) are not translated (that’s a problem). It’s against the [Best Practices for XML Internationalization](http://www.w3.org/TR/xml-i18n-bp/#DevAttributes) to put user-readable content into attributes; I think we could easily change the questionnaire schema to fix that?

I have tried to simulate a questionnaire development by changing a source (English) string that was already translated into Czech. After updating the resource in Transifex, the string was marked as untranslated. That’s very helpful for the translation teams when the English source changes. I have also tried to switch the order of two lines to test the translation “anchors”. After updating the resource in Transifex, both strings were marked as untranslated (that’s not perfect, but at least helpful) and correct previous translation was suggested (nice).

Transifex can also [watch public URLs for changes](http://docs.transifex.com/faq/#can-i-update-source-files-automatically) so that if we include the questionnaire XLIFF in the repository, changes in the English translation can be pushed to translation teams automatically.

**Comment by zoul** [comment]
As I was proofreading the current Czech translation spreadsheet (#1046) I noticed a lot of errors that have crept in. Most of them look like they were caused by the translation process, ie. the conversion from XML to the spreadsheet and back:

* There’s machine translation in some places. I am fairly sure there was none the last time I edited the document. It’s very unfortunate to have machine-translated strings appering in the human-translated document, since the machine translation quality is terrible (non-usable) and it’s very hard to spot new machine-translated strings in the whole spreadsheet.

* Some strings were missing a part (a sentence ending in the middle), some strings were joined together where they shouldn’t be, whitespace sometimes appears where it shouldn’t (and where it makes difference both in XML and HTML).

Some parts of the Open Data Certificate UI come from the RoR app itself, others come from the questionnaire. Some strings from the spreadsheet end up in the questionnaire, others will only appear on the final certificate. Also, the dynamic branching nature of the questionnaire makes it harder to ever spot some of the strings in the live app, since it means you have to tweak various answers until you hit the right combination. That’s the nature of the app and I’m not complaining, but it makes it harder to come up with a high-quality translation, since the translator doesn’t have a clear idea about the context a phrase appears in. We need a better localization process so that we can iterate quickly and fix errors as we spot them on the live app.

I’m happy to put code where my mouth is, at least as far as I can manage – if there’s interest.

**Comment by sumikasan** [comment]
@pkqk - I will see if I can find two other alternative solutions to the Transifex for evaluation. (no more than 3 days spike for each)

@zoul - we are planning to analyse what options we have to get the localisation streamlined; if you know any other applications than Transifex please let us know.

**Comment by pkqk** [comment]
@sumikasan this looks like another alternative https://poeditor.com/help/

**Comment by pkqk** [comment]
@zoul I'm looking at putting the translations into a proper tool now, currently Transifex and I'll try out the XLIFF conversion.

I'll look at changing the schema for the questionnaire, have you got any other recommendations for best practice?

Also would it help to have a page with all the questions expanded and visible at the same time for proofreading translations?

**Comment by zoul** [comment]
Great! I don’t have any schema suggestions apart from turning the localizable attributes into elements. Having all the questions expanded at the same time would be very nice indeed :+1: 

I don’t have any tool recommendations besides Transifex, and even Transifex I mentioned just because I have seen [Discourse](http://www.discourse.org) using it. There’s a [long thread over at Discourse](https://meta.discourse.org/t/translation-tools-transifex-localeapp/7763) about l10n tools – I don’t have the time to read it at the moment, but there may be pointers to other tools or thoughts there.

**Comment by sumikasan** [comment]
@pkqk - another solution worth reviewing, aside from POEditor:
https://crowdin.com/

**Comment by pkqk** [comment]
It looks like based on features and price Transifex is the right one to go for.

I think the best plan is to move to keeping the questionnaire for each jurisdiction be in English and then use the generated .yml file to apply translations to the correct language for the jurisdiction. Storing the translations in .yml isn't as featureful as a proper translation format but there appear to be very few tools for .xlff and .yml is the rails default.

This will mean vetting and checking the questionnaire will be possible in both languages and we'll be able to provide a UI that switches between languages.

I've tested importing the questionnaire into Transifex with the languages we have at the moment and it looks usable. The only tricky issue I see will be the dealing with differences between the legal section without duplicating most of the questionnaire for each jurisdiction.

**Comment by pkqk** [comment]
Tasks needed to move to Transifex

  - Move source questionnaires back to English
  - And set up `.yml` files as extra languages for each jurisdictions questinnaires.
  - Re import questionnaires into surveyor.
  - add missing interface translations to Transifex. (boolean yes/no questions etc)
  - possibly create automated workflow for downloading new translations.

**Comment by pkqk** [comment]
This ticket has been split up into #1151, #1152, #1153, #1154, #1155
