### ISSUE TITLE
Cant add LinkedIn URL as social media account

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#1069]
Trying to create a certificate and when answering the question "Which social media accounts can people reach you on?" I supplied the URL https://www.linkedin.com/company/3998?trk=tyah.

The application told me that this isn't valid (it is!)

**Comment by pkqk** [comment]
Requests seem to be returning an annoyingly invalid `999 Request denied` response and it looks they are blanket blocking hosting provider IP ranges. Their `robots.txt` includes this:

```
User-agent: *
Disallow: /

# Notice: If you would like to crawl LinkedIn,
# please email whitelistcrawl@linkedin.com to apply 
# for white listing. 
```

We could:
  1. skip the http check for linkedin URLs
  2. use the linkedin api to attempt to validate them
  3. apply for permission to spider but it looks like they only allow the big google/msn/baidu bots.

**Comment by JeniT** [comment]
How irritating. Skip the check for Linkedin URLs.

**Comment by sumikasan** [comment]
I will contact LinedIn in the meantime

Sumika

On Wednesday, 15 April 2015, Jeni Tennison <notifications@github.com> wrote:

> How irritating. Skip the check for Linkedin URLs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/open-data-certificate/issues/1069#issuecomment-93248063>
> .
>


-- 
Sumika Sakanishi

Product & Project Manager

*Open Data Institute*
3rd Floor, 65 Clifton Street, London EC2A 4JE
http://theodi.org
