### ISSUE TITLE
As an admin I'd like to see how users have answered a specific question

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#1079]
For example, looking at some stats at how users have answered a specific question in their certificate, and then be able to view a certificate.

Specific use case: 

* for "What kind of release is this?" how many certificates are associated with each answer?
* then, can I get links to those certificates, so I can explore those that are "an ongoing release of a series of related datasets"

**Comment by sumikasan** [comment]
This will be addressed when we allow the data dump of all the certificates published as open data for everyone to analyse.
See #1184
