### ISSUE TITLE
Changing jurisdictions duplicates the certificate

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#1083]
I created a certificate under the GB jurisdiction then later changed it to the correct country.

After I did that and saved the questionnaire, I ended up with two draft certificates. Is this intentional?

Screenshot:

![cert](https://cloud.githubusercontent.com/assets/109082/7274697/f2172a10-e8f6-11e4-9486-d5e2f81c08ab.png)

**Comment by JeniT** [comment]
I think that is intentional: you can have completely different questions under a different jurisdiction, which means that you might lose the answers that you've given in your previous version. You can always delete the additional draft if you're confident you don't need it.
