### ISSUE TITLE
CKAN import task assumes answers to get basic certificate

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1090]
There are some questions where the answer the is hard to get from the ckan api or from heuristics on it.

In [the dcat extraction code](https://github.com/theodi/open-data-certificate/blob/master/app/models/kitten_data.rb#L119) it sets the answers to a few questions without consideration.

Of these questions 
  - `publisherOrigin`
  - `dataPersonal`
  - `contentRights`
  - `codelists`
  - `vocabulary`

Are the only ones required to get a Raw certificate (which based on my reading of [certificate.en.xml](https://github.com/theodi/open-data-certificate/blob/master/prototype/translations/certificate.en.xml) only `publisherOrigin` and `contentRights` should be required for raw, the others are set to pilot/standard, so maybe the survey generation isn't correct?)

The `publisherOrigin` question is: Was all this data originally created or gathered by you?
which I don't think we can answer without checking.

  - `dataPersonal` is Can individuals be identified from this data?
  - `contentRights` is Is there any copyright in the content of this data?

which are both hard to answer automatically and:

  - `codelists` is Are there any codes used in this data?
  - `vocabulary` is Do the data formats use vocabularies or schemas?

which defaulting to `no` is probably ok.

These assumptions have already been applied to the data.gov.uk datasets, @JeniT @sumikasan does it seem reasonable to extend it to all automatically imported datasets or should we find ways to determine these answers or look into why they are being required for a raw certificate?

**Comment by JeniT** [comment]
I think it's reasonable to make the assumptions that it's making as default values. Government shouldn't be publishing data (under an open licence) if they don't have the right to, or if it contains personal data, or if it contains unlicensed content.

**Comment by pkqk** [comment]
Does the US Government have the same requirements for publishing as the UK Government?

**Comment by sumikasan** [comment]
@JeniT : there is an inconsistency between the survey and the XML description re: the condition for getting raw vs pilot/standard for codelist and vocabulary.

Please clarify which option to go with:
  1. need codelist/vacab for getting the RAW?
  2. this is for >Pilot

**Comment by sumikasan** [comment]
Looks like there is a bug, hence the question.

**Comment by JeniT** [comment]
@pkqk the questions in the US certificate are slightly different (especially around legal issues), but yes.

@sumikasan you shouldn't need to get codelists/vocab to get a raw certificate. There's no problem in those questions being answered in the auto-generated certificates, but they could equally be left unanswered.

**Comment by pkqk** [comment]
I've looked into the certificate verification and the way it works out dependencies isn't quite correct. So questions that are required for higher level certificates are currently considered required if they have no dependent questions.
