### ISSUE TITLE
Unit tests don't pass if wall clock is between 00:00 and 01:00

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1092]
DateTime math is incorrect

tests in
  - `certificate_test`
  - `stat_test`
  - `embed_stat_test`

**Comment by JeniT** [comment]
Good grief

**Comment by pezholio** [comment]
Is this a BST / GMT thing?

**Comment by pkqk** [comment]
After a quick look, I discovered this at 0:55 so didn't have much time to locate it, I think it's tests assuming an hour ago is on the same day.

Probably not a big deal apart from the fact that it is testing stat collection so the aggregation over times may be incorrect.

**Comment by sumikasan** [comment]
@pkqk - let's review this when we are discussing re:stats for dashboard etc.
