### ISSUE TITLE
Multiple possible entry questions should display in cert entry with all answers made so far

### ISSUE THREAD

**Issue by SeivadLR** [theodi/open-data-certificate#1103]
when trying to track down broken links on a certficate it is very difficult to trace all the broken links. You have to keep on clicking the add button until you get an empty box to ensure that you have picked up all the links.  This is annoying and time wasting.

**Comment by shevski** [comment]
@SeivadLR could you add some steps to reproduce and/or screenshot and what's the main pain point?

**Comment by rachelwilson** [comment]
Closing as so much time has passed
