### ISSUE TITLE
Auto-certification: dataset that earned raw certificate failed to be published

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#1117]
From the recent pilot run for N. Yorkshire - see http://staging.certificates.theodi.org/campaigns/10

The following dataset failed to be published, despite passing the raw level criteria:
Fraud Information for North Yorkshire Fire and Rescue Service

**Comment by pkqk** [comment]
This is caused the same issue that is causing Glasgow to fail.

The SSL certificate chain isn't set up correctly on https://www.northyorksfire.gov.uk so the URL checker is failing it.

The certificate is only published if it reaches the correct level and if all the urls provided in the questionnaire work correctly.

**Comment by pkqk** [comment]
It does need to show this better in the interface though

**Comment by sumikasan** [comment]
Took the link off, so I hear this should work now. Could we re-run the programme again?
