### ISSUE TITLE
Consider newer CC licenses?

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1122]
This [Leeds dataset](http://leedsdatamill.org/dataset/current-incidents-information-feed) is licensed under CC BY-SA of an unspecified version.

Though the description page it links to implies that it could be version 4.0 which is suitable as a data license as well as for content.

Our code is currently only aware of CC BY-SA 2.0 UK as a content license.

Should we consider more of the CC licenses acceptable for a Certificate? @JeniT @sumikasan

**Comment by Stephen-Gates** [comment]
Queensland is moving to adopt CC BY 4.0 as default, so yes please.

**Comment by sumikasan** [comment]
Yes definitely and suggest we also ask which version (like when answer 'other') as a follow up (drop down then specify the version or link to its definition is even better). Any thoughts?

**Comment by Stephen-Gates** [comment]
@sumikasan not sure on the best user interface approach for this. Ideally the licence and version is detected from the metadata.
