### ISSUE TITLE
Retry if a certificate generation fails

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1140]
If a `CertificateGenerator` task fails there needs to be some retry logic if the failure was due to internet connectivity. Otherwise intermittent failures cause the certificate generation campaign to not include all datasets.

**Comment by pezholio** [comment]
So, are we talking about the client's internet connection being down, or the target server having a temporary issue?

**Comment by pkqk** [comment]
Both cases really, you can't rely on every request being successful. The extreme example is healthdata.gov where last time I was testing it every 2nd or so request would 500.

So if a certificate is queued up to be created from a site it should try a few times before marking it as failed, and also give the option to requeue it later maybe.
