### ISSUE TITLE
verifying links on https domains with incorrect SSL setups

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1141]
If the dataset or links inside the dataset are served via https and the certificate chain is not being served correctly our fetching code will fail.

The pages will appear correct in Chrome and often Firefox and Safari as browsers include many intermediate certificates in their bundles. We're using the ubuntu `ca-certificates` bundle which doesn't seem to include many intermediate certificates.

We could either:
  1. Add to the bundle on each machine
  2. Add a way to add extra certificates to ODC.
  3. Get each website to set their servers up properly.

**Comment by ross-os** [comment]
After the 2015-06-01 #1143 deploy, we are no longer able to see the ODI badge on the https://www.ordnancesurvey.co.uk/opendatadownload/products.html site.

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://certificates.theodi.org/datasets/591/certificates/14859/badge.js. (Reason: CORS header 'Access-Control-Allow-Origin' missing).```

```This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.```

Is there a way to fix this or will it require the creation of a new SSL certificate?

**Comment by pkqk** [comment]
hi @ross-os, that's nothing to do with this SSL issue.

I made changes to the CORS header setup and forgot that there are .js files as well as .json files that need access. I'll get that fixed.

**Comment by pkqk** [comment]
The warning is in relation to our SSL certificate not yours, as SHA-1 is now considered weak.

**Comment by shevski** [comment]
Unclear which site this effected, re-raise if this becomes an issue again.
