### ISSUE TITLE
updating a response set to a newer questionnaire is unusably slow.

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1142]
The code that copies `response`s from one `response_set` to a new one when the questionnaire has been updated is too slow to respond to a browser in time.

The current data model suffers from many n+1 query issues which I think is the main cause of this problem.

**Comment by LR-Technology-Group** [comment]
Any news on when this is going to be addressed.  this has stopped LR certification efforts completely.

**Comment by pkqk** [comment]
@LR-Technology-Group it's going to take quite a bit of time to solve this fully.

If you can send me links to the certificates you're working on I can update them to the newest questionnaire manually so that when you go to edit them it should be faster.

**Comment by LR-Technology-Group** [comment]
Chasing  When is this likely to be resolved.  I Cannot edit LR certificates AT ALL  because I get service unavailable after waiting for minutes. 
Service Unavailable

The service is temporarily unavailable. Please try again later

**Comment by pkqk** [comment]
@LR-Technology-Group I had made some work around changes to try and improve this but they had to be reverted as they caused even worse bugs.

You can edit certificates you just need to avoid pressing 'Continue', each individual change is saved as you make them, it's the final update which resaves everything which causes the Service Unavailable error.

If you then navigate straight to the dashboard (https://certificates.theodi.org/users/dashboard) you can publish the certificates.

I can't give an accurate estimate on fixing it as it requires quite a significant rewrite of internal code but it is the primary thing I'm working on at the moment.

**Comment by LR-Technology-Group** [comment]
Hi Adam,

Thanks for this.  After your email I have been able to edit a certificate.  (Up until lunchtime clicking the edit button in the dashboard was giving me the message.  I hadn’t even begun to edit anything.

Does this mean I can do the work over several days as I am unlikely to complete the certificate entryin a single day.   Before I am ready to publish.

Regards

George Davies  (also SeivadLR in GITHUB).

mailto://george.davies@landregistry.gsi.gov.uk

**Comment by pkqk** [comment]
@LR-Technology-Group yes, every individual change you make is saved immediately. You can either bookmark the form page or use the dashboard to get back to editing them. It's only the 'Continue' button that causes the issues.

If clicking 'Edit' caused a problem it's because the answers were for an older set of questions and it had to update it to the newer questionnaire. This is a similar speed problem to the 'Continue' issue and will be fixed by the same work.

**Comment by pkqk** [comment]
The number of update queries have been reduced to a manageable number that the pages no longer time out at the load balancer.

There are still some issues caused by generating the interface, and the US questionnaire causes many more loads than the UK questionnaire for some reason.
