### ISSUE TITLE
Jurisdiction selector doesn't use latest data

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1150]
The way the jurisdiction selector is implemented causes several problems.

  - It's loaded dynamically by the world map generator.
  - It doesn't use the latest data as the selecting the latest of a set of versioned rows is very difficult in ActiveRecord. This means it doesn't show updated:
    - survey names
    - relevant alpha/beta/live statuses of questionnaires.

**Comment by shevski** [comment]
no longer have world map on homepage
