### ISSUE TITLE
Alter XSLT/Surveyor localisation workflow to support Transifex

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1153]
- [x] Revert Czech jurisdiction questionnaire files to English
  - [x] Alter the XSLT/Surveyor to make and consume `.yaml` files usable by Transifex/Rails i18n
  - [x] Make SurveyBuilder use i18n files for translations.

**Comment by sumikasan** [comment]
@pkqk is this finished yet?

**Comment by pkqk** [comment]
@sumikasan I merged it in with Czech adapted to the new Transifex setup on friday.

So Yes.
