### ISSUE TITLE
Can't change jurisdiction

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#1158]
Get error message trying to change jurisdiction before creating a certificate (not logged in)

**Comment by pezholio** [comment]
Yup, just had the same here too

**Comment by pezholio** [comment]
Appears to be a 404

**Comment by pkqk** [comment]
@Stephen-Gates do you mean selecting which jurisdiction to fill the questionnaire in for doesn't work or you can't change one you've already started?

**Comment by Stephen-Gates** [comment]
I select Create a Certifcate, Continue without registering, Choose a new jurisdiction (before starting the questionnaire), then...
![screenshot 2015-06-05 19 53 19](https://cloud.githubusercontent.com/assets/9379524/8003628/9452cefa-0bbc-11e5-9903-ed749fa195d5.png)

**Comment by pkqk** [comment]
Yeah I just tried a few different flows before, it appears to completely not work when not logged in.

**Comment by pkqk** [comment]
Narrowed this down, it was introduced by the fixes for #1133.

The change jurisdiction form is using a GET request as well.
