### ISSUE TITLE
Apply the work-around solution to fix the timeout issue on a couple of draft Expert certificates

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#1166]
A number of certificates are not editable because they are timing out. Rather than wait for the overall fix to optimise the performance, please apply a work-around solution so that the publisher can edit and save their certificates?

These are:
https://certificates.theodi.org/datasets/1621/certificates/48561
https://certificates.theodi.org/datasets/1709/certificates/48635

**Comment by sumikasan** [comment]
More edit is required so this needs to be implemented.

**Comment by pkqk** [comment]
@sumikasan both the certificates are using the most up to date questionnaire so editing won't be slow.

Pressing the 'save and finish' however will take a long time and time out.

They can bypass this by going straight to the 'My Certificates' page and pressing publish there. Everything is saved as they go so the save+finish button can be skipped.

**Comment by pkqk** [comment]
They can now edit the questionnaires quickly again.
