### ISSUE TITLE
Determine Country/Jurisdiction based on Geo IP lookup

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1177]
Suggest or determine which jurisdiction the questionnaire should be filled in for based on the browsers origin.

MaxMind GeoIP database is free and semi decent.
http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by Stephen-Gates** [comment]
Very supportive of this idea - yes please

**Comment by Stephen-Gates** [comment]
As an alternative provide a switch in the URL to set the jurisdiction  e.g. https://certificates.theodi.org/au or something similar.

**Comment by pkqk** [comment]
Using the `Accept-Language` header looks like it's also valid now* too http://code.flickr.net/2009/12/04/language-detection-a-witchs-brew/

* well for ages, just superstition has made people think otherwise
