### ISSUE TITLE
Document what metadata is used to answer questionnaire

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1186]
What metadata from what formats are used to answer questions.

**Comment by Stephen-Gates** [comment]
@pkqk it would be great if this information was added to https://certificates.theodi.org/en/autocertification

**Comment by pkqk** [comment]
attn: @pezholio @Floppy @shevski 

Hi @Stephen-Gates, I'm no longer at the ODI so @pezholio is the person to prod now.

**Comment by Floppy** [comment]
Hey @pkqk just because it's 8 years ago doesn't get you off the hook
