### ISSUE TITLE
No manual answer or change for questions dealing with machine-readable data

### ISSUE THREAD

**Issue by jgkim** [theodi/open-data-certificate#1201]
Machine-readable data should be gathered and processed in an automated manner. So, questions dealing with machine-readable data should not be able to be answered or changed manually. When the answer is not collected correctly, that means the data has some problems, preventing the 'machine' to process the data properly.

**Comment by Stephen-Gates** [comment]
@jgkim I like this idea. It provides:
- answers through evidence, rather than yes/no
- less manual answers to complete 

My only concern is, can be performed automatically with an acceptable response time?

**Comment by jgkim** [comment]
@Stephen-Gates I think a response time would not be a problem. Actually, the current version of the ODI ODC tries to answer some questions automatically by using the DCAT vocabulary.

**Comment by shevski** [comment]
This has been improved recently for ckan datasets and will add to future roadmap for better machine readable support
