### ISSUE TITLE
Decided airbrake reporting environment from environment

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1206]
Set an `AIRBRAKE_ENV` envvar so we can report airbrake failures to the correct environment.

**Comment by pikesley** [comment]
I'm presuming I'm going to set this to 'staging'. Sound OK?

**Comment by pikesley** [comment]
Or we could have 'certs-staging' or something, if that make more sense. Ideas?

**Comment by pkqk** [comment]
Just `staging` makes sense, it's already per project by the other airbrake settings

**Comment by pikesley** [comment]
OK

**Comment by pikesley** [comment]
This now exists, it will enter the field of play on the next deploy (which we'll need in order to make use of it anyway, I guess)

**Comment by pkqk** [comment]
Cleaned up via https://github.com/theodi/open-data-certificate/pull/1207
