### ISSUE TITLE
Schema for questionnaire defintion files

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1208]
Is there a schema xsd or something similar @jenit for the certificate.xml files? Some of the translators have been editing it and naturally it's ended up in a invalid state and I just discovered a line duplication bug I probably introduced when merging.

It would be good to be able to run schema checks on the files as part of the test suite.

**Comment by quadrophobiac** [comment]
Examples of where correctly formed tags is unclear
```
<yesno required="required"/>
<yesno required="required" yes="open data sources" />
<yesno required="pilot" yes="anonymised" />
```

**Comment by shevski** [comment]
closing unless something specifically actionable to do here? cc @JeniT
