### ISSUE TITLE
Try upgrading to at least ruby 2.0

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1210]
Ruby 1.9.3 was end-of-life'd in February, I've been running it on 2.0.0p481 as that is the default Ruby on Yosemite without issues.

Since we're almost ready to release it on new infrastructure we could try it on a newer ppa package of ruby?

**Comment by pikesley** [comment]
Yes, I think I can spin one up without too much trouble. Will get to this today.

**Comment by pikesley** [comment]
Attempting this has thrown up a bug in my cookbooks, kind of glad it's surfaced now...

**Comment by pikesley** [comment]
It lives: http://experimental.certificates.theodi.org/

If this works OK (and it looks good so far) we can upgrade all the nodes to this

**Comment by Floppy** [comment]
amazing!

**Comment by Floppy** [comment]
@pikesley @pkqk can this close now?
