### ISSUE TITLE
Certificate flowcharts missing questions

### ISSUE THREAD

**Issue by bcouston** [theodi/open-data-certificate#1216]
Currently exhibited in the Legal flowchart there are missing questions (for example piaAudited in certificate.GB.xml). This is because they have a dependency on questions that have a text input answer that currently are not registered as "answers" in flow.rb as said by @pezholio. Only questions with radio button answer structure or similar are registered as answers.  Therefore a {question} !== "" test is not parsed correctly. Quick solution is to move question with this dependency to immediately after the question it depended on, now excluding the dependency. This has been attempted with copyrightStatementMetadata already.

**Comment by pkqk** [comment]
I mentioned to @pezholio this morning that it might be better to use the `Survey`, `SurveySection`, `Question`, `Answer` and `Dependency` models instead of reparsing the xml file.

This means you'll only have one flowchart per jurisdiction and you don't have to read any xml.
