### ISSUE TITLE
Add the web app localization file as a resource to Transifex

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1235]
I would like to start translating the web app itself (ie. the [locales folder](https://github.com/theodi/open-data-certificate/tree/staging/config/locales)). It looks like it’s not on Transifex yet – the [Resources group there](https://www.transifex.com/theodi/certificates/content/) only contains the survey. Can somebody please add a new resource for the app localization?

At the moment I don’t need any fancy workflow with the strings going automatically back and forth, I just want to load the strings into Transifex, translate them into Czech and create a pull request for the translated version once I’m done.

(As for the file format, the Ruby YAML localization format should be supported out of the box by Transifex.)

**Comment by pkqk** [comment]
@zoul I've added the current locales files, they aren't complete but there it's something to get started with.

**Comment by zoul** [comment]
Perfect, thanks!
