### ISSUE TITLE
Improve code support for pluralization

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1236]
There’s a slight localization problem with plurals, caused by code like this:

```ruby
# localization string is like “this certificate will expire in %{days} days”
notice = t('certificate.expiring_notice',
    jurisdiction: @certificate.response_set.jurisdiction,
    days: @certificate.days_to_expiry)
```

The code is correct, but oversimplifies the issue of localizing singulars and plurals. Even in English it will happily produce messages like “this certificate will expire in 1 days”, in other languages the mismatch can be worse.

Here’s a [great general essay about the issue](http://search.cpan.org/~toddr/Locale-Maketext-1.26/lib/Locale/Maketext/TPJ13.pod) and here’s an [official Rails Internationalization API Howto](http://guides.rubyonrails.org/i18n.html) that hints how the problem can be tackled in Ruby (see section 4.3):

```ruby
I18n.backend.store_translations :en, inbox: {
  one: 'one message',
  other: '%{count} messages'
}
I18n.translate :inbox, count: 2
# => '2 messages'
 
I18n.translate :inbox, count: 1
# => 'one message'
```

**Comment by zoul** [comment]
(There is a more general l10n issue lurking here: the messages in the app are often created by simply concatenating several strings together. This usually works in English, but can be much more problematic in other languages that are more context-dependent.)

**Comment by tonymarklove** [comment]
Transifex has impressed me again, it looks like it has very nice support for these, as you can see here: https://www.transifex.com/theodi/certificates/translate/#cs/website/65134637?key=expiring_notice

I have added plurals for `certificate.expiring_notice` as you mentioned above, and one other obvious location. They are quite hard to spot in the site though, so if you notice any more just let me know.
