### ISSUE TITLE
Add a language switch to the website

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1238]
It is currently possible to switch the questionnaire language (where available), but I am aware of no way to switch the language for the whole website. For example, if I arrive at a [random certificate from the Czech jurisdiction](https://certificates.theodi.org/datasets/26511/certificate) and my browser says I speak Czech, I would like the certificate to be displayed in Czech.

* The default language could be autodetected from the browser.
* There should be a persistent override somewhere in the UI, like a dropdown with a list of supported languages.
* The active language should also affect the embed code for the certificate and the badge.
* I’m not sure how the site-wide language switch should interact with the language switcher in the questionnaire. I guess it should replace it altogether?
* The active language could also be used as a reasonable default for the questionnaire jurisdiction.

**Comment by pkqk** [comment]
be aware of 553fe93a5c5bdf695d75a1ace7d7222187cf3301 the javascript will need to be fixed and then the adding of the `locale` param enabled again for locale switching to work
