### ISSUE TITLE
data.gov.uk failing to validate on existing certificate repairing Described question

### ISSUE THREAD

**Issue by LR-Technology-Group** [theodi/open-data-certificate#1239]
changing the where is data described question, because it has the publisher information not the data location.
![image](https://cloud.githubusercontent.com/assets/5636851/9792184/c34d5dd6-57d6-11e5-8e19-26524a51b85b.png)
cannot get past the validation screen  It was saying a problem has ocurred now it just looks as above.

the full URL is
'http://data.gov.uk/dataset/land-registry-monthly-price-paid-data'

this is a CKAN dataset.
I cannot change the URL.  I have to Back out and leave it unamended.

**Comment by LR-Technology-Group** [comment]
Now validates , but see

**Comment by shevski** [comment]
Bug described here https://github.com/theodi/open-data-certificate/issues/1265
