### ISSUE TITLE
Provide more context for the localization

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1240]
When translating the strings from the web app, a translator needs to know the context each string appears in. Otherwise it’s hard to come up with a decent translation, or even a correct one. Currently the strings in the `locale` folder don’t have much context in them – the translator often has to guess where a string appears in the UI. This isn’t very effective and sometimes the particular part of the UI is hard to discover, for example the screens for transferring a certificate ownership.

It would be great if the localization teams had access to up-to-date screenshots of all the UI screens. I don’t know how your software specification looks like, but if you have something like user stories, that would be a perfect resource for localization (when augmented with screenshots).

Speaking for the Czech l10n team, this doesn’t prevent us from reaching the first shipping milestone, but would be _very_ beneficial for the quality of the localized product.

**Comment by rachelwilson** [comment]
Closing, as so much time has passed this team no longer exists
