### ISSUE TITLE
Is this data public domain appearing only on Property transaction dataset

### ISSUE THREAD

**Issue by LR-Technology-Group** [theodi/open-data-certificate#1256]
Question appearing on old converted certificate.  No way to remove it.  deleted certififcate and re-created.  question was NOT displayed (same as the other certificates.)

**Comment by shevski** [comment]
@LR-Technology-Group Do you have a link to this?

The public domain question appears when you answer 'no, the data only contains facts and numbers' to 'Is there any copyright in the content of this data?' as a further bonus point - that is, if there's no copyright, then why not make it clear it's public domain.

Was the question appearing at different times for you? Why did you want to remove it?

**Comment by rachelwilson** [comment]
Closing, since so much time has passed
