### ISSUE TITLE
Certificate level & badge localization

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1274]
We’re currently scratching our heads over the certificate level localization. There are four certificate levels available: Raw, Pilot, Standard, and Expert. It’s unfortunate that there is no obvious ordering on these levels, even in English – for example, if you see the certificate for the first time, is a Raw certificate better than a Pilot one? And once we translate the level names into Czech, there will be an extra issue of comparing the Czech level names to their English counterparts (“what do they call the Raw level again?”).

What would you think about renaming the levels to something more neutral, like metals? Bronze, Silver, Gold, and Platinum, for example. There’s an obvious ordering, the translation into other languages is obvious, and as a bonus you would get a (more or less) obvious way to translate the level names into graphical badges.

**Comment by zoul** [comment]
Speaking of the graphical badge, the current look (a big ODI logo) doesn’t really work well in the Czech context, and I suspect it will be the same case with other localizations. A metal badge saying something like “Certified Open Data” would work much better, and you can always add a smaller “by ODI” tagline to promote the ODI brand.

**Comment by dicknorris** [comment]
Hi Tomáš - we've also been thinking the same thing.  It's our plan to go through a rebranding exercise soon.  Will keep you posted.

**Comment by zoul** [comment]
Great, thanks!

**Comment by zoul** [comment]
We have tried the “medal versions” in the Czech localization and they seem to work very well.

**Comment by Stephen-Gates** [comment]
In Australian we've previously discussed Bronze, Silver, Gold, Platinum with the ODI. Raw and Pilot are confusing and not enticing when we speak about it to potential local adopters. Everyone gets the Olympic medal concept. In fact, I recently used the idea [in a presentation](https://twitter.com/ODIQueensland/status/664607904964612097) to the Queensland Government.

We're holding back on localisation until the rebranding is done as we don't want to confuse early adopters and consumers.

**Comment by zoul** [comment]
We needed to localize the levels anyway, and since the general concepts of _Raw_ and _Pilot_ were quite hard to translate meaningfully, we went for the medals right away. I agree it’s going to be a bit confusing if anyone compares the Czech certificates to some English ones, until the English ones are also converted to medals.
