### ISSUE TITLE
Remove SurveyTranslation model

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1275]
Make the translation just use Rails I18n system from files. Removing the `@@variable` cache hack from [survey.rb](https://github.com/theodi/open-data-certificate/blob/staging/app/models/survey.rb#L150) too

It will make updating translations easier and requires database access when rendering a questionnaire.

There may also be some better ways to write helpers or middleware with the Rails I18n setup.

**Comment by tonymarklove** [comment]
How do we want to do versioning of translations if we don't use the database? Correct me if I'm wrong but at the moment when you create a survey it is locked to the set of questions and translations that exist at that moment.

**Comment by pkqk** [comment]
Since most translation changes have been typos or corrections I don't think locking questionnaires to old translations is a good solution.

It is possible though that a change to the wording could change the meaning of the question and what the answers meant but I don't think it's worth keeping the complexity to support that situation as it will be less common.

**Comment by tonymarklove** [comment]
Done and deployed.
