### ISSUE TITLE
Activated higher level questions can prevent a lower level certificate from being achieved

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1281]
@shevski helped identify that when a question that is a requirement for standard or expert is triggered it can prevent a pilot certificate from being obtained.

If a question has two possible answers, one that is required for a standard level and one that satisfies pilot level then the requirement will not be marked as met for pilot, bumping the achieved level down to raw.

**Comment by pkqk** [comment]
Once fixed this will need an update to be run on existing certificates to recalculate the levels, as some may be attaining Pilot or higher that they are currently not marked as.

**Comment by SeivadLR** [comment]
It is also possible that the LR scenario was this.  The certificates were "continue"d prior to being fully complete.  Once all sections were answered,  the dashboard did not refresh,  although the sidebar and the "improve" sections both were.
