### ISSUE TITLE
Make account confirmation workflow localizable

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1285]
I have created an account on the staging server under Czech locale, but the confirmation e-mail I received was in English and the _Confirm my account_ link also appears to go to the website using English locale.

**Comment by zoul** [comment]
Since I am going to file more issues that have popped up in the localized webapp interface, would you like me to file them elsewhere, over at `theodi/shared` maybe?

**Comment by tonymarklove** [comment]
I think keeping them in this repository is fine. We can pull across any that are big stories when we do sprint planning.
