### ISSUE TITLE
Unlocalized strings in the web app interface

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1287]
I have translated all strings available on Transifex in the “website” resource (as of October 7th). Looking at [the Czech version of the website](http://staging.certificates.theodi.org/cs/) now, the following strings are still in English. Maybe they are hardcoded or didn’t properly propagate to Transifex?

* [x] Home page: _Account_ and _Logout_
* [x] User profile: _Name_ input label, _Organization_, _Default jurisdiction_, _Preferred locale_, _Password_, _Password confirmation_, _Current password_, _Authentication token_
* [x] User dashboard: _Your certificate_, _Publish certificate_, _View certificate_, _Your answers_, _Edit Questionnaire_, _Change Jurisdiction_, _Delete_
* [x] Certificate display page: _Not Applicable_ (as a value for the License field), _Title With Level_ (the tooltip says: `translation missing: cs.levels.title_with_level`)
* [x] Dataset list (`/datasets`): _Subscribe to these results…_, _Download complete set…_, _Published By_, _Issued_, _View certificate_, paging buttons (_Next_, _Last_). In the advanced search: _Jurisdiction_ (a label on the jurisdiction filter)
* [x] Site-wide: jurisdiction list (such as in advanced search). The countries mostly appear in English.
* [x] The first auto-certification screen of the questionnaire: _Link to the dataset you are certifying…_, _If your data is stored in a CKAN_, _Skip this_, _Check URL_, _I don’t have a URL_, _Read more about Open Data Certificates_, _There was a problem with your URL…_ (a popover on the _Check URL_ button).
* [x] Questionnaire form: _Edit_ button (next to the documentation URL), _Untitled_ (as a placeholder for a not-yet-named dataset).
* [x] Certificate deletion confirmation box: _Cancel_ button.

I will expand the list as I find new unlocalized strings. It’s quite possible that some of these are our mistakes – please tell us.

**Comment by tonymarklove** [comment]
Thanks for this. It is quite easy for me to miss individual strings when I'm looking through the code, so keeping this list updated with anything you spot is very useful.

**Comment by tonymarklove** [comment]
All of the points in the list are now translatable. Some of these are new strings that have now been pushed to Transifex, so they should show up in the 'untranslated' tab.

**Comment by zoul** [comment]
Perfect, thanks :+1:
