### ISSUE TITLE
Optionally turn off the automatic certification step for some jurisdictions

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1289]
The very first screen on each certification form asks for a documentation URL. If I understand things correctly, this is the URL that could be used to fill the certificate automatically. In the Czech jurisdiction the automatic certification won’t be used at all, everyone will simply click the _Skip this_ button. Would it be possible to turn off the screen for the Czech jurisdiction? We may return it later, but for now it just gets in the way.

**Comment by tonymarklove** [comment]
How come it would never be used in the Czech jurisdiction? It is a big time-saver if anyone has data already described with CKAN or DCAT.

**Comment by zoul** [comment]
Sorry, this was a misunderstanding on our side. I’ll need to test the process on some Czech datasets and improve the copywriting, but the autocertification _is_ useful. Again, sorry for the noise! :gun:
