### ISSUE TITLE
Make contacts localizable

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1290]
I’m not sure how to properly localize the jurisdiction contacts:

![contact](https://cloud.githubusercontent.com/assets/95329/10333137/309646bc-6ce2-11e5-9e1a-00f0e77cbf1d.png)

On one hand, you probably don’t want to receive the direct Czech feedback on your main contact e-mail or here in the main repo. (The institutions don’t always speak English and the approach doesn’t scale.) On the other hand, if we change the contacts to display the Czech localization team info, the same text gets displayed for all jurisdictions:

![changed contacts](https://cloud.githubusercontent.com/assets/95329/10333224/ca726d10-6ce2-11e5-8aa3-9a69fb56b2c8.png)

This doesn’t make much sense either – it makes it look as though we are responsible for the Ghana jurisdiction, too. A nice solution would be introducing a list of contacts for different jurisdictions? Then if a jurisdiction has its own localization team, we would display their contact info, and if not, the generic English contacts would appear.

**Comment by shevski** [comment]
No longer relevant now that's gone from homepage as far as I can tell, shout if not!
