### ISSUE TITLE
Make relative dates localizable

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1292]
In the dataset list, there’s a string stating the last update time of a dataset – _15 minutes ago_, for example. This string needs to be localized. The string is composed of two parts, _15 minutes_ and _ago_. This won’t do for other languages, the localization code has to build the whole string. (For example, in Czech the correct translation would be _před 15 minutami_, ie. the „ago“ part needs to be in front of the rest.)

**Comment by tonymarklove** [comment]
@zoul the rails helper we are currently using for translation will use the translations you can see [here at line 57](https://github.com/svenfuchs/rails-i18n/blob/6f810360f3bb1b468e23ee29192fec8616567a45/rails/locale/af.yml#L57). So everything under the heading `distance_in_words` are the possible results. Do all those make sense with "před" in front, or will you need more control than that?

**Comment by zoul** [comment]
Technically, _před_ in front of these strings will sometimes feel a bit awkward. For example, _about a month ago_ would render as _před asi měsícem_, while the best option would be _asi před měsícem_. But since [the Czech locale for the helper](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/cs.yml) looks already complete, I’d say let’s use it, it’s a great start. We can return to the issue later if needed. Thanks a lot!
