### ISSUE TITLE
Make static pages localizable

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1293]
Eventually we would like to translate static pages such as the terms of use, privacy policy, etc. How do we technically go about that? I don’t mind translating the raw source files, no need to pull Transifex into the process here.

**Comment by tonymarklove** [comment]
I was thinking about this and I think a combination of editing the source + Transifex will work well. It looks like Transifex can support whole HTML files (counting it like one giant string) so we may as well do that for consistency, and so Transifex can give us stats.

Basically what this means is simply having a directory of files like: `about.en.html`, `about.cs.html`, etc. Then each translation can be edited as a whole.

**Comment by zoul** [comment]
Will the Transifex UI work for such long strings? It seems to be designed for smaller ones. Let’s see. Can you make the necessary changes and add a new resource to Transifex? (This is not a high priority at the moment.) Thanks!

**Comment by tonymarklove** [comment]
Not sure. It seems to say that it should work in the documentation but I haven't tried it yet. Either way you will still be able to edit the files directly.

**Comment by tonymarklove** [comment]
@zoul and @pkqk 

Finally getting around to testing this. I have uploaded a test of the About page to Transifex. This turns the [source HTML](https://github.com/theodi/open-data-certificate/blob/staging/app/views/pages/about.html.erb) into [this Transifex translation](https://www.transifex.com/theodi/certificates/translate/#cs/pages-about/64882905).

At first glance it looks very promising. Unfortunately it strips any Ruby ERB that it finds which won't work when we pull down the translated files from Transifex for use in the site. So we have a few options:

1. **Remove and don't use any ERB on static pages**. For most pages this is not a big problem. There is not much ERB in the first place. But we do use quite a bit of ERB to build the FAQs with a nice table of contents at the top, so there will always be places where it is useful.
2. **Don't use Transifex for these files**. As I mention above, I have split the static page files by locale. So now there is `about.en.html.erb` and `contact.en.html.erb`, for example. We could simply do translations by creating `about.cs.html.erb`, translating that file, and committing it.
3. **Mix of the two**. Any of this can be done on a file-by-file basis where it makes sense.

Any thoughts from either of you about what makes the most sense, now and for future translations?

**Comment by zoul** [comment]
Great work, thanks! Now that I can see the interface in practice, I think the Transifex’s way of treating resources as collections of strings doesn’t work very well with longer texts logically divided into paragraphs. It’s quite common for a translator to leave a sentence out or reshuffle the sentence order, for example. The Transifex UI doesn’t quite support that. Not to mention that some of these texts need _localizing_ in the more general sense, adapting them for the target country instead of simply translating. So I vote for localizing those resources ad-hoc, just committing them into the repo without any explicit tooling support. And we can keep the ERB markup.

The only serious downside I can see is that the translation teams won’t be notified of changes in the base English localization automatically. But I don’t think that’s a show stopper at the moment.

**Comment by tonymarklove** [comment]
Ok, that's definitely fine for now at least. We can always review the process if other translators get involved in the future, or we have problems.

I'll get the renamed files merged into the main `staging` branch. Then you can feel free to go in and translate all the files in `app/views/pages`, and create a pull request.
