### ISSUE TITLE
Can’t edit translations in Transifex after review

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1332]
Some translations were imported to Transifex from older formats and were marked as Reviewed by pkqk:

![sample translated and reviewed string](https://cloud.githubusercontent.com/assets/95329/10877429/68087b10-8146-11e5-8417-eb961d73d789.png)

But once the string was marked as Reviewed, it’s not possible to edit it anymore, as stated in the [Transifex FAQ](http://docs.transifex.com/faq/):

> Last but not least, there is the role of the Reviewer. This person proofreads the translations and once approved, translators are unable to edit the string.

Which means that I as a translator can’t update the translations as needed. I don’t know how the roles work on Transifex – is it possible to make me a kind of “manager” of the Czech translation team so that we could sort these issues out on our own?

**Comment by tonymarklove** [comment]
@pkqk I don't have rights to make any changes to permissions, so this one is down to you.

**Comment by pkqk** [comment]
@zoul ah sorry, I wasn't aware of that interaction restriction. I've set everything to be unreviewed now.

I'd thought it would be a good way to set translations up for staging and live release.

**Comment by zoul** [comment]
I wasn’t aware of the restrictions either. Thanks!
