### ISSUE TITLE
Certificate data shown in English although the site and jurisdiction are set to Czech

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1334]
I have created a testing certificate in the Czech jurisdiction and the Czech locale, but when I view the certificate, most of the values in the certificate are in English:

![screenshot of the problem](https://cloud.githubusercontent.com/assets/95329/10878322/21f618ba-814d-11e5-8947-559af721ab13.png)

**Comment by tonymarklove** [comment]
This should already be fixed by the work in #1322, which will get merged to staging shortly.

**Comment by zoul** [comment]
Confirmed fixed, thank you!
