### ISSUE TITLE
translation merge task is combining english over the translated text

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1341]
For the `surveyor.survey_sections.practical.*` keys even though they are translated in Transifex they are being pulled down as English.

**Comment by pkqk** [comment]
also should translations be being updated by a `tx pull` or by `rake translations:pull[xx]`?

**Comment by tonymarklove** [comment]
I think either `tx pull` or `rake translations:pull[xx]` should work. I've mainly been doing the steps manually, but `rake translations:pull[xx]` should do the pull and then ru the rake task to merge the resulting locale file.
