### ISSUE TITLE
FAQ typo

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#1352]
On https://certificates.theodi.org/en/faq#how-useful-are-certificates-to-re-users, 
"How **does** you demonstrate that the data has been certified?"
should be,
"How **do** you demonstrate that the data has been certified?"

**Comment by shevski** [comment]
direct link https://certificates.theodi.org/en/faq#how-does-you-demonstrate-that-the-data-has-been-certified
@pezholio could you update?

**Comment by pkqk** [comment]
see 9ed3261ff5741b6f2e3c0ac86b366a777577bfe1
