### ISSUE TITLE
Requirements generated from enumerating xml file don't match up

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1353]
With the requirements generated from the xml file based on an index in the loop means that they don't match up with the English translations.

Need to generate deterministic identifiers, or have a better model for modelling requirements

This has shown up with the Czech localisation removing a branch of questions, and now that the jurisdiction translations are all matched up instead of being per localisation they end up mismatching.

**Comment by shevski** [comment]
Serious major translation bug 😱
