### ISSUE TITLE
deleting a published certificate doesn't revert to old certificates

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1357]
the state machine updates don't consider this scenario.

**Comment by shevski** [comment]
What should the logic be around superseded versions and deleting draft or published or past versions of certificates?

Currently deleting current OR superseded version just deletes it. Nothing else happens.
Should it be possible to delete published certificates? Once deleted, should previous superseded version become 'current' and editable? Where should previously published but now deleted certificate URL resolve to? A 404 or previous version? 
Can't currently edit or improve superseded versions, so deleting current leaves you with no next step (?)
