### ISSUE TITLE
Can we replace the promotion video on the home page?

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1359]
We wanted to localize the YouTube video on the home page by supplying subtitles, but in the end we would rather replace the video with [a fitting Czech one](https://www.youtube.com/watch?v=L6B4qhuFt30). Would it be possible to do that in the Czech language version of the website?

**Comment by shevski** [comment]
Don't see why not! Although we've chosen to remove the video completely for the website update.
