### ISSUE TITLE
Embed option for WordPress?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#1381]
- I am moving the ODI Queensland site to http://queensland.theodi.org, a Wordpress site ODIHQ has provided.
- I have a page that lists [Australia's Open Data Portals](http://queensland.theodi.org/home/resources/data/)
- I have exported a CSV file from the TablePress table and added it to Google Drive.
- I have earned a [certificate](https://certificates.theodi.org/en/datasets/213485/certificate)
- When I paste the certificate embed code into Wordpress, it gets ignored.

Is there a way I can embed the badge on a WordPress page? 

---

Later:
I just found this [documentation](http://codex.wordpress.org/Using_Javascript#JavaScript_in_Posts) in the WordPress Codex.

Now battling with WordPress which keeps stripping out the code despite following the instructions

--- 

Later still:
It seems adding a Plugin to WordPress may be the easiest way to address this but I don't think I have permission to do that.

**Comment by pezholio** [comment]
Hey Stephen

Have asked Phil to get in touch with you regarding getting the plugin added. Will close this now

**Comment by Stephen-Gates** [comment]
@pezholio thanks.

**Comment by langphil** [comment]
Hi @Stephen-Gates there should be something in there for you now. I've sent an email over confirming.

**Comment by Stephen-Gates** [comment]
@langphil @pezholio, Thank you. Plug-in installed.

Reading the documentation now to try get things working
