### ISSUE TITLE
Duplicate questions on FAQ?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#1386]
It seems to me that these two FAQS are very similar:

- [What are the benefits of Open Data Certificate to reusers?](https://certificates.theodi.org/en/faq#what-are-the-benefits-of-open-data-certificate-to-reusers)
-  [How useful are certificates to re-users?](https://certificates.theodi.org/en/faq#how-useful-are-certificates-to-re-users)

Perhaps the second question should be reworded:
- How will we ensure open data certificates continue to provide value to re-users?

**Comment by shevski** [comment]
Yep. I suggest we just remove the second question (How useful are certificates to re-users?)
