### ISSUE TITLE
The main page does not work in IE11

### ISSUE THREAD

**Issue by mormegil-cz** [theodi/open-data-certificate#1387]
The site is ±completely broken in IE11 for me (while in Edge, it seems to work fine). An _Invalid character_ error in application.js (in the HTML encoder or whatisthat using an I-believe-valid-but-a-bit-strange `ˇ:"caron"` syntax, which IE seems not to accept, erroneously, [it seems](http://unicode.org/cldr/utility/character.jsp?a=02C7).) and after that, an _'$' is undefined_ error on the main page cause the scripts to die, and therefore e.g. the _Create a certificate link_ leads to https://certificates.theodi.org/en/surveys#start-cert-modal instead of displaying the modal dialog.

(Copied from #1365 which was strangely closed with “create a new issue if it's still a problem”.)

**Comment by shevski** [comment]
Another IE styling bug: https://github.com/theodi/open-data-certificate/issues/428
