### ISSUE TITLE
Certificate logo changes in right pop-out window going from Bronze to Silver

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#1389]
As I change an answer that takes me from Bronze to Silver, the logo in the right pop-out window changes. I think the logo shouldn't change based on the [recent re-branding](http://theodi.org/news/open-data-certificate-update-012016).

Bronze:  
<img width="1390" alt="screenshot 2016-02-23 06 14 00" src="https://cloud.githubusercontent.com/assets/9379524/13231354/413ceff4-d9f5-11e5-94bd-a0205d17c5c6.png">

Silver:
<img width="1366" alt="screenshot 2016-02-23 06 14 22" src="https://cloud.githubusercontent.com/assets/9379524/13231355/415bc5dc-d9f5-11e5-827d-91e0cc57b6a0.png">

**Comment by shevski** [comment]
Impressive attention to detail @Stephen-Gates thank you!
