### ISSUE TITLE
create a certificate - all website links cannot find page

### ISSUE THREAD

**Issue by LynnHeeley** [theodi/open-data-certificate#1399]
all the links relating to creating a new certificate state that they cannot find the page (or are circular back to the start page). I presume you do not have to be registered to make these work?

**Comment by pezholio** [comment]
Hi, can you give me an example of a link that's causing you issues? You should see a prompt telling you to sign in, or continue without signing in. Also, what browser are you using?

**Comment by LynnHeeley** [comment]
The main link for creating a certificate (https://certificates.theodi.org/en/) now seems to work, sorry for slow response. thanks
