### ISSUE TITLE
Identify what needs customising for each autocertification run

### ISSUE THREAD

**Issue by Floppy** [theodi/open-data-certificate#1413]

**Comment by digitalWestie** [comment]
Stuart's suggestions:
- publisher name
- publisher url

**Comment by pezholio** [comment]
Also license related questions, as shown in https://github.com/theodi/open-data-certificate/blob/staging/app/models/kitten_data.rb#L162-L172

I think, as a minimum, it'll be worth looking at all metadata items specified in [DCAT](https://www.w3.org/TR/vocab-dcat/)

**Comment by Floppy** [comment]
Idea: could a user choose a part-filled draft certificate to copy default values from? Like a template?

**Comment by digitalWestie** [comment]
Plan: Allow user to select from one of their draft certificates of the same jurisdiction.
