### ISSUE TITLE
Create UI to allow creation of an autocertification run

### ISSUE THREAD

**Issue by Floppy** [theodi/open-data-certificate#1414]
We want to be able to run an autocertification of a CKAN portal from a simple UI in the web interface.

Needs to:

* Enter a CKAN URL
* Configure required options including language and jurisdiction
* Do a test run of (say) 10 datasets
* View errors

**Comment by Stephen-Gates** [comment]
And given #1419 optionally enter CKAN Organisation (e.g. https://data.gov.au/organization/city-of-hobart)
