### ISSUE TITLE
View in-progress certification run

### ISSUE THREAD

**Issue by Floppy** [theodi/open-data-certificate#1416]
Once a run is started through the admin UI, we'll want to be able to leave it, and go back to check on progress.

Should include a measure of how many succeeded and failed. Also, if things fail, we should be able to drill into the details to find out why.

**Comment by pezholio** [comment]
Might be worth using https://pusher.com/ to report back to the frontend regularly maybe?

**Comment by digitalWestie** [comment]
What do we actually mean by 'success' ? Is it that the data was grabbed successfully and didn't fall over? Or do we mean that there weren't enough responses to give it a certificate level?

**Comment by digitalWestie** [comment]
I've begun writing a report page but I'm realising this is mostly covered at the moment. The campaign show page displays how many are in progress and shows if responses are missing etc.

**Comment by digitalWestie** [comment]
I've had another look at the campaign show page. Although it shows what's  worked / failed etc, it doesn't have the original value of how many datasets it added to the queue. So most of what's described here is currently covered but the page could be improved quite a bit with a queue count.

**Comment by digitalWestie** [comment]
Todo: add a campaign dataset count.
