### ISSUE TITLE
Campaign autocert doesn't handle links to other data portals

### ISSUE THREAD

**Issue by digitalWestie** [theodi/open-data-certificate#1436]
Campaigns pick up datasets that are really hosted on other portals. The result is it tries to fetch dataset meta from the wrong url.

The following search shows a few examples of these datasets:     

http://data.sa.gov.au/data/dataset?q=threatened+species+state+lists&sort=extras_harvest_portal+asc%2C+score+desc%2C+metadata_modified+desc

Check out the ones tagged 'FROM DATA.GOV.AU'

**Comment by Stephen-Gates** [comment]
There's a fair bit of cross harvesting on Australian portals. Some call it the "no wrong door" approach. So wherever you go, you'll find all the links. Data.gov.au and data.sa.gov.au do this the most. Not every Government has adopted the idea.

**Comment by Floppy** [comment]
Decision is:

* By default, ignore datasets that are harvested from other portals, to avoid duplication of certificates.
* Add an option in the campaign to include harvested datasets in the campaign (work in progress in #1442)

**Comment by digitalWestie** [comment]
I've updated #1442 to do the above :+1:

**Comment by Stephen-Gates** [comment]
suggest this can be closed based on #1442
