### ISSUE TITLE
Feature infrastructure for ODCs

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/open-data-certificate#1537]
_From @Floppy on August 17, 2015 13:6_

_Copied from original issue: theodi/shared#700_

**Comment by quadrophobiac** [comment]
_From @Floppy on August 17, 2015 13:6_

Talk to @pkqk about what this should be.

**Comment by quadrophobiac** [comment]
_From @pikesley on August 17, 2015 13:7_

I suspect we can do this with Heroku

**Comment by quadrophobiac** [comment]
_From @dicknorris on August 21, 2015 16:36_

Book to  ODM  > WP3 > Task 3.5

**Comment by rachelwilson** [comment]
I thiiiink the reference to ODM might be this: https://docs.google.com/document/d/1y5Yo8bFUoDjCQLCnQXWQNX23c0ZJiGk8JjF3stORbjc/edit

Too much time has passed now so closing this
