### ISSUE TITLE
Run auto-certification campaign for open.canada.ca (Canada) on live

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/open-data-certificate#1539]
_From @dicknorris on September 18, 2015 15:50_

_Copied from original issue: theodi/shared#754_

**Comment by Stephen-Gates** [comment]
Probably not done given only one certificate awarded to Canada https://certificates.theodi.org/en/datasets?utf8=✓&search=&datahub=&level=&jurisdiction=ca

**Comment by rachelwilson** [comment]
closed during backlog review - so much time has passed this one is no longer relevant
