### ISSUE TITLE
"Check URL" fails

### ISSUE THREAD

**Issue by olivierthereaux** [theodi/open-data-certificate#1695]
### Summary

Automated URL checks are failing, creating a significant barrier to use of the tool.

### How to reproduce

1. Create new certificate
2. Enter a (valid) URL

Expected Behaviour: the URL is checked automatically and some metadata is extracted if possible

Current behaviour: the "Check URL" button shows an exclamation mark and the UI offers a form field requesting a justification of why the URL is incorrect.

![Screenshot 2019-04-11 10 16 27](https://user-images.githubusercontent.com/604646/55945560-f3d61000-5c42-11e9-9253-563d1c6769f7.png)

### Severity and related issues

This is problematic in two ways:
- It slows down the process dramatically
- It is misleading the user into thinking that the problem is on their side, when it is not. This is compounded by the poor usability highlighted in #1263

**Comment by olivierthereaux** [comment]
Early diagnosis: the asynchronous PUT call to start.json appears to return a 404. I doubt that is the expected behaviour.

![Screenshot 2019-04-11 10 22 08](https://user-images.githubusercontent.com/604646/55946021-cb9ae100-5c43-11e9-8e7d-d80e7e012b34.png)

**Comment by olivierthereaux** [comment]
Further diagnosis shows that the issue is not with every URL, but only some. We suspected it may have something to do with the fact that the automated check is done by ODIbot, which identifies itself with the user-agent _ODICertBot 1.0 (+https://certificates.theodi.org/)_.

Quick check showed that indeed this would cause some CDNs to block the bot.

As a quick fix, attempting to change the UA: https://github.com/theodi/open-data-certificate/commit/d64e6950cb8fc3421b29311721deb89af6f6499c

Ideally we would also improve the error message to not make it look like the problem is necessarily the user's fault.

**Comment by rachelwilson** [comment]
See also https://github.com/theodi/open-data-certificate/issues/1194
