### ISSUE TITLE
Questionnaire - progress bars need to be simplified

### ISSUE THREAD

**Issue by JeniT** [theodi/open-data-certificate#270]
(From @agentGav)

It isn't clear how the progress bars work, with the different progress on different levels.

An alternative approach would be to have one progress bar that simply indicates the proportion of the currently visible questions that have been answered. The text above the progress bar, and the badge used, can indicate what level has been attained.

**Comment by pkqk** [comment]
I've made it so only the progress bar for the current level you are working towards is visible
