### ISSUE TITLE
Questionnaire - The ODI level indicator is open from the start and is difficult to close on the iPad.

### ISSUE THREAD

**Issue by john-stephenson** [theodi/open-data-certificate#343]
1.  Load into the Questionnaire.
2.  Look at the ODI level indicator.
3.  Attempt to close it.

[Result]

The level indicator is open automatically as you load into the form and is difficult to close.

Sometimes, selecting a field will close it, however most of the time it will just stay open.

As a result the descriptive text and part of the field are obscured from view.

![odi level indicator is difficult to close](https://f.cloud.github.com/assets/2317741/662608/1c960d98-d75a-11e2-9921-a568bcfe9b2c.png)

**Comment by pkqk** [comment]
We can change behaviour of the badge indicator to show/hide the panel. Currently it acts as a toggle to stop it autohiding on desktop.
