### ISSUE TITLE
Change embed code to use the certificates badge URL not a direct link

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#393]
Currently the HTML snippet provided to users includes a link like this:

```html
<a href="http://certificates.theodi.org/certificates/96">
<img alt="Pilot_level_badge" src="https://certificates.theodi.org/assets/badges/pilot_level_badge.png" />
</a>
```

It might be better to use the /badge URL for the certificate, e.g.:

```html
<a href="http://certificates.theodi.org/certificates/96">
<img alt="Pilot_level_badge" src="http://certificates.theodi.org/certificates/96/badge" />
</a>
```

(With the ability to link to the "latest certificate" links, as described in #375 the links could be even more general, e.g. /dataset/certificate/latest and /dataset/certificate/latest/badge)

**Comment by pkqk** [comment]
The embed code is now an iframe with no references apart from `dataset id` which will not change when the state of a certificate changes.
