### ISSUE TITLE
Search & search results

### ISSUE THREAD

**Issue by jolankester** [theodi/open-data-certificate#436]
@beckyjennings' sketches for the search dropdown and results page. 

![odi-search1](https://f.cloud.github.com/assets/2854757/884639/7113a75c-f9bc-11e2-80c4-076cd633441f.jpg)
![odi-search2](https://f.cloud.github.com/assets/2854757/884640/7113699a-f9bc-11e2-9da7-7f830bc25403.jpg)
![odi-search-results](https://f.cloud.github.com/assets/2854757/884641/7353ce98-f9bc-11e2-88be-ca997706048a.jpg)

**Comment by sumikasan** [comment]
Review later when we will be looking at search functionality
