### ISSUE TITLE
Consolidate Dataset Views 

### ISSUE THREAD

**Issue by benfoxall** [theodi/open-data-certificate#584]
We've revised the datasets index view.  It would be awesome if we could extend this to support the dashboard view too.

@jolankester to look at on Monday

---

### Current index view

![image](https://f.cloud.github.com/assets/51385/1138996/31d46020-1c82-11e3-9c22-3cc2abbb7ef9.png)

### Current dashboard view

![image](https://f.cloud.github.com/assets/51385/1138985/0b9025ca-1c82-11e3-8cf6-cc147773c687.png)

**Comment by pkqk** [comment]
Closing as this what this even is appears to be forgotten about.
