### ISSUE TITLE
Varying sizes of Fonts used in certificate questionnaire entry give poor user experience

### ISSUE THREAD

**Issue by LR-Technology-Group** [theodi/open-data-certificate#612]
Questions are answered in different ways with different font sizes used, for instance, license drop down gives its answer in smaller text than the normal for the page,  URL boxes have a very large font that means it is not possible to read the whole URL without attempting to click into the box and then scroll the text.  Could make URLs font smaller and or increase the width of the URL entry box, or Wrap the longer strings.  Making all the answers the same size would also be helpful.

**Comment by pkqk** [comment]
needs a more severe redesign.
