### ISSUE TITLE
Juvia Https -> http include problem

### ISSUE THREAD

**Issue by benfoxall** [theodi/open-data-certificate#658]
The juvia comment script can't be loaded because the juvia endpoint is http rather than https:

![image](https://f.cloud.github.com/assets/51385/1464248/d36814ac-4542-11e3-97c2-d7668c03125c.png)

Two solutions to this:

* support https - https://juvia.theodi.org (best)
* provide a local proxy in the certificates app (might be a good placeholder)

**Comment by pkqk** [comment]
This is a problem again @pikesley after the new chef changes.

**Comment by pikesley** [comment]
I did not, but it's easier to fix now

**Comment by pkqk** [comment]
I think we should fix the nginx/https setup but I think I'll also look into making the juvia plugin not susceptible to this.

**Comment by pikesley** [comment]
Right, so this https://juvia.theodi.org/ works

Is it that we need to *enforce* https?

**Comment by pkqk** [comment]
no it's the app needs to know what protocol it's on for generating urls

**Comment by pkqk** [comment]
Fixed by setting the envar `JUVIA_BASE_URL` to `https://juvia.theodi.org`
