### ISSUE TITLE
Search box styling on Firefox

### ISSUE THREAD

**Issue by ProjectDavis** [theodi/open-data-certificate#680]
Go button not aligned with search box on Firefox 

![tinygrab screen shot 07-11-2013 12 59 21](https://f.cloud.github.com/assets/4105469/1491832/3d278154-47b7-11e3-96ab-297623e9ae47.png)

**Comment by pkqk** [comment]
![screen shot 2015-01-13 at 11 22 46](https://cloud.githubusercontent.com/assets/5235/5720036/88028dfa-9b16-11e4-8827-ac7252beaf0a.png)

looks ok now
