### ISSUE TITLE
Rename country label "Taiwan, Province of China"

### ISSUE THREAD

**Issue by tomheath** [theodi/open-data-certificate#682]
In the jurisdictions dropdown, next to the globe on the homepage, Taiwan is referred to as "Taiwan, Province of China". This is presumably the label taken directly from the ISO_3166-1 country list, in which Taiwan has the country code "TW", and would seem to reflect UN politics rather than administrative reality or the situation on the ground with regard to data licensing:
http://en.wikipedia.org/wiki/Taiwan,_China#Use_in_the_UN_and_other_instances
Would suggest renaming to just "Taiwan".

**Comment by audreyt** [comment]
Hi, is this change deployed to certificates.theodi.org ?

In https://certificates.theodi.org/surveys/gb/qYWl5oLckw/start when I click "Switch jurisdiction":

![2015-05-26 4 05 36](https://cloud.githubusercontent.com/assets/20723/7801768/a1ca49f4-035c-11e5-91a2-567e1421d895.png)

the dropdown still lists the pre-fixed value:

![2015-05-26 4 04 32](https://cloud.githubusercontent.com/assets/20723/7801755/684ef350-035c-11e5-9a69-9f5d18839f20.png)

Thanks for looking into it!

**Comment by pkqk** [comment]
This is caused by #1150, I've solved this particular instance by renaming the old questionnaires in the database to just `Taiwan`
