### ISSUE TITLE
UX task: Review of knowing what you need to answer to reach a particular level i.e. "this is required for pilot"

### ISSUE THREAD

**Issue by beckyjennings** [theodi/open-data-certificate#731]
Hi @JeniT, @ProjectDavis 

I've started working on this today. Having looked at the questionnaire with a fresh pair of eyes, I had a lot of questions and discussed them with Jo and Pete. We realised that there are a few actions/icons/messages that are confusing to the end user. 

I've suggested that I go through the questionnaire and pick out the top 10 issues and suggest solutions (I'll do this as a google presentation with screenshots and sketches). Holly has agreed that I can spend about a day on this. Can we then have a meeting/call to go through the issues?

**Comment by sumikasan** [comment]
Closed - will review as part of the UI / UX review.
