### ISSUE TITLE
Bulk download of all certificates

### ISSUE THREAD

**Issue by JeniT** [theodi/open-data-certificate#754]
We should provide a bulk download of all the data about the certificates (ie the same information that is available in JSON), in a CSV file.

**Comment by pkqk** [comment]
Is it ok to just flatten all the fields in the `.json` description into columns for CSV?

Also currently the `.json` version of [certificates.theodi.org/datasets](https://certificates.theodi.org/datasets.json) only shows the first 20 datasets as it's paginated by default.

There is not defined way to do pagination in `.json` or `.csv` like there is in `.atom` or `.html`, for `.json` I could use [JSON Hyper Schema](http://json-schema.org/latest/json-schema-hypermedia.html) to define the next/prev links or include them in [HTTP Link](https://tools.ietf.org/html/rfc5988) headers which would also work for `.csv` format.

The other option is to make `.json` and `.csv` be entire downloads of the database.

**Comment by JeniT** [comment]
I think the CSV should be a dump of everything; flattening the JSON for that should be fine.

I think the JSON should probably still be paginated. Including next and prev links in the JSON is good. If it's easy to also use Link headers, do that too.

**Comment by pkqk** [comment]
I had to make the csv download be a pre-generated dump as the app server can't stream responses and fetching the full set takes about 20 minutes of queries.

It also means you can't request subsets as `csv` which is a shame.

After deploying I did notice a problem which I'm not sure how to fix. The site is served from a cluster of machines but if I generate the `.csv` in the background it will only update on disk for one server in the cluster. I'm not sure how to get a job to run on all the nodes.

**Comment by JeniT** [comment]
Could the dumped CSV file be put somewhere else (eg cloud storage, Google doc, file in Github) and referenced from there?

**Comment by pkqk** [comment]
@JeniT yeah that would work, there is some other code that looks like it might put stuff on rackspace. I could base off that.
