### ISSUE TITLE
Always asked for reference to a feed of releases

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#846]
When I'm completing a certificate in the Location section I'm asked:

"How do you publish a series of the same dataset?"

No matter what the answer is I'm always asked to provide a link to a feed of changes. But I'd expect that if I say "as a single URL that's regularly updated", then I've said that there isn't a feed, so the box shouldn't appear?

Seems valid to show it for the other two options

**Comment by sumikasan** [comment]
@ldodds - questions have been updated - please review to see if this is still a problem in which case, can you create a new ticket with an explanation on what the problem is.
