### ISSUE TITLE
Documentation URL question doesn't respect language / jurisdiction

### ISSUE THREAD

**Issue by pezholio** [theodi/open-data-certificate#854]
When someone selects a different jurisdiction to UK, the documentation URL question is always in English. This appears to be hardcoded into the template, so needs fixing.

**Comment by pkqk** [comment]
@sumikasan looking through the conversation on #855 it seems like we do have the translations for that bit of the page. I'll see if I can adapt @pezholio's changes.

**Comment by pkqk** [comment]
Merging this, even though it is incomplete it's an improvement.
