### ISSUE TITLE
datasetUrl redirect returns an error if dataset isn't found

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#859]
A URL like:

https://certificates.theodi.org/datasets?datasetUrl=http://data.ordnancesurvey.co.uk/datasets/code-point-open

redirects to the latest certificate for the dataset with that url. But if you use an unknown URL, e.g:

https://certificates.theodi.org/datasets?datasetUrl=http://example.org

Then you get a 500 error. Should be a 400, perhaps with a custom page that indicates that the user could add a new certificate?

**Comment by pkqk** [comment]
It's currently returning the standard 404 page.

That's not very informative but not incorrect, and this isn't a commonly used feature at the moment.
