### ISSUE TITLE
Duplicated error correction line on certificate

### ISSUE THREAD

**Issue by Floppy** [theodi/open-data-certificate#860]
See https://certificates.theodi.org/datasets/2533/certificates/14894, practical section.

![screen shot 2014-09-05 at 16 21 31](https://cloud.githubusercontent.com/assets/3565/4167100/5cdbd120-3510-11e4-9d65-d32a38b4b427.png)

**Comment by pkqk** [comment]
Two responses to that question have been recorded.

I've fixed this instance but I'm not sure how the duplication could've happened.
