### ISSUE TITLE
Email notification to dataset owners with auto-generated certificates

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#863]
As an ODC Administrator,
I want to notify the dataset owner that the certificates are available,
So that they can claim (i.e. take the ownership) the certificates.

Acceptance Criteria
Scenario 1: Dataset owner with multiple certificates
Given that a contact has more than one certificates generated
And the datasets are from the single publisher
Then the system will send a single notification email
And not one email per dataset 

Scenario 2: Dataset owner assigned to multiple publishers
Given that a contact has more than one certificates generated 
And the datasets are from more than one publisher
Then the system will send a single notification email per publisher

**Comment by pkqk** [comment]
On the 5th of December I sent David Read a csv of all data.gov.uk certificates with the associated email address and password reset links. I think they were going to send an internal mail around.

**Comment by pkqk** [comment]
@sumikasan based on the discussions with David Reed, should we close this for now?
