### ISSUE TITLE
Capturing additional information about the new user

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#865]
As an ODC Administrator
I want to capture more information about the user account holder
So that I can provide a personalised product support.

As a Data Owner,
I want to edit the contact details when claiming my certificate(s)
So that I can take the ownership of the user account to manage the certificate(s) for my dataset(s)

Basic requirements:
1. User clicks the link from the notification email to claim the certificates associated with the user account
2. User will be presented with a user registration form
3. User must provide the following information to complete the process:
- Name of the person claiming the user account the the certificates
- Email address that was used to create the account
- Organisation name (of the user claiming the certificates)
- Checked the tick-box to demonstrate that acceptance of Terms & conditions

**Comment by pkqk** [comment]
I think there should be some UX discussion about the requirement for the user's name and organization.

They are not displayed externally so there is no incentive for the user to provide them and some may just be individuals and no data is better than a collection of 'nope', 'n/a', '-' etc that all mean the same thing.
