### ISSUE TITLE
Pilot certificate showing us no level on certificate page

### ISSUE THREAD

**Issue by statshero** [theodi/open-data-certificate#883]
https://certificates.theodi.org/datasets/2534/certificates/14895

(Certificate is unpublished.)

![screen shot 2014-09-12 at 13 44 11](https://cloud.githubusercontent.com/assets/1837585/4249686/83a24dba-3a7a-11e4-8c5e-5b6ee177aa32.png)

![screen shot 2014-09-12 at 13 44 32](https://cloud.githubusercontent.com/assets/1837585/4249689/917f57b6-3a7a-11e4-98ac-d4c03a32eaa8.png)

**Comment by pkqk** [comment]
It now shows No level in both areas, it doesn't look like it has enough answers to qualify for Pilot so the template must have been choosing that in error at some point.
