### ISSUE TITLE
Publish Privacy and Cookie policies

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#887]
Privacy policy and Cookie policy documents are missing on Open Data Certificate website.
Links to be available from the footer:

![links](https://cloud.githubusercontent.com/assets/7251962/4284028/3961f476-3d77-11e4-99e4-02a5e15500d0.png)

**Comment by pkqk** [comment]
Should the Privacy policy and Cookie policy just be links to the main ODI site or copies of the documents or different documents entirely?

**Comment by JeniT** [comment]
I think they need to be different because we have accounts on the certificates site, unlike on the main site. I suspect that you'll want some text? Can you do a branch and give me a pointer to the docs to edit?

**Comment by pkqk** [comment]
Yep, I'll make some empty pages to put stuff in. I checked and there's probably content that needs to be added to the main theodi.org site too, there is a [`__cfduid`](https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-) cookie from cloudflare and google analytics has changed so also sets cookies called `_ga` and `__gat`

This site will set one called `_open-data-certificate_session` as that's the rails session cookie.

**Comment by pkqk** [comment]
@JeniT I've made a branch on #1017 that you can add to.

There is example content in both markdown or haml, depending on which substandard markup format you prefer.
