### ISSUE TITLE
Claiming auto-generated account by email

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#899]
As a Data Owner,
I want to claim the certificates for my datasets (when contacted by email)
So that I can manage them

Also see: Email notification to dataset owners with auto-generated certificates
https://github.com/theodi/open-data-certificate/issues/863

Basic requirements:
1. User receives an email from the ODI instructing me to claim the certificates
2. User clicks 'Claim the certificates' link in the email
3. User completes the verification process to claim the certificates.

**Comment by pkqk** [comment]
If emails have been sent out by David Read as mentioned in #863 then following the password reset link should be enough to complete this step.
