### ISSUE TITLE
Publisher list

### ISSUE THREAD

**Issue by rossjones** [theodi/open-data-certificate#908]
It would be great to be able to find a list of publisher names for those that have certificates.  Even better if they were identifiable so that I was able to tell GLA is the same as Greater London Authority is the same Gtr London Authority.

I'm not sure whether http://reference.data.gov.uk/ only covers central departments or not, but something that identifies the publisher for matching that means I don't have to run my own http://nomenklatura.okfnlabs.org/ would be awesome.

**Comment by pkqk** [comment]
do this as part of #1184
