### ISSUE TITLE
Guidance Notes need Pointers to Examples

### ISSUE THREAD

**Issue by tomheath** [theodi/open-data-certificate#91]
The guidance notes work really well from an interface point of view, but in several cases leave the user hanging, not being sure where to go next. Example:

"If you have a copyright statement, it is good to embed within it machine-readable information about the licence under which you are making your data available. We can use this to automatically fill in parts of this questionnaire. Others can use it to automatically create attribution statements when they reuse your data."

This really needs a link to an example of a copyright statement with machine-readable information [nb. whats the distinction here between information and data?] embedded so that users have a reference point to work from, or can at least envisage what this looks like.

**Comment by sumikasan** [comment]
@ldodds can you please provide the draft for this to go into the help text / improvement page

**Comment by sumikasan** [comment]
@ldodds - please ignore; @tomheath we have updated the help text; if you think this is still useful then please let us know exactly which help text should be updated to provide the comments

**Comment by pkqk** [comment]
The help text is at https://github.com/theodi/open-data-certificate/blob/staging/prototype/jurisdictions/certificate.GB.xml#L357
