### ISSUE TITLE
DocumentationUrl Should or Must

### ISSUE THREAD

**Issue by jmatsushita** [theodi/open-data-certificate#984]
Hi @JeniT,

I guess this type of discussion should happen more in the comment threads but until #969 is fixed, I thought I'd capture my question here.

I don't quite understand the logic behind the current requirement for raw/pilot with regards to DocumentationUrl here: 
https://github.com/theodi/open-data-certificate/blob/master/prototype/translations/certificate.en.xml#L27-L32

It seems that maybe for a one-off dataset publication maybe having a documentation would give more kudos, but for collections, series or services shouldn't they be a minimum? Or maybe I'm missing something?

Cheers,

Jun

**Comment by rachelwilson** [comment]
Closing as so much time has passed and the institutional knowledge is lost :(
