### ISSUE TITLE
documentFormat labels 

### ISSUE THREAD

**Issue by jmatsushita** [theodi/open-data-certificate#985]
Hi @JeniT,

Also something to move to comment threads when #969 is closed. It took me a while to understand the last option of the documentFormat question. 

    Do your human-readable documents include formats that
     - describe semantic structure like HTML, Docbook or Markdown
     - describe information on formatting like OOXML or PDF
     - aren't meant for documents like Excel, JSON or CSV

I think the confusion is the use of the term document when usually people talk about Excel documents. Maybe using the formulation __aren't generally used for human-readable documents__ would help? 

Also talking about OOXML or PDF as describing information on formatting is something that I guess mostly techies would know. Maybe using __formatted document types__ or __documents generally used for printing__

Then maybe there is an exemplar level: Semantically annotated formats like HTML with RDFa or microformats?

Cheers,

Jun

**Comment by sumikasan** [comment]
@jmatsushita - we just made some changes to the questionnaire wording / help texts, but I would welcome your input that is better phrased?
