### ISSUE TITLE
'/improvements' page - How can I improve my open data?

### ISSUE THREAD

**Issue by jmatsushita** [theodi/open-data-certificate#986]
In the 'How can I improve my open data?' page it seems that it would help legibility and the cognitive burden of moving from the form to the improvement page if some of the structural elements of the form itself where present specifically:
 1. the top group (and maybe even sub-group) for the field - i.e. Technical or Technical / Formats
 2. (possible) the name of the field (instead of just the question) - making it easy to speak about (i.e. did you fill the "data title" field? instead of did you fill the "what's this data called" field?)

There are some possible twists in the details for 2/ since some fields don't have a visible field name (only the text and url fields as far as I can see).

So the current structure:

Basics | 
:--------- |
What's this data called? | 
Who publishes this data? | 
... | 
Are there any codes used in this data? | 
**Pilot** |
You should put timestamps in your data when you release it so people know the period it relates to and when it will expire. |
... | 

Would become with 1.:

Basics | Question | 
:--------- | ---- | 
General  | What's this data called? | 
General | Who publishes this data? | 
... | ...
Social - Documentation | Are there any codes used in this data? | 
**Pilot** | **Question** | 
Practical - Accuracy | You should put timestamps in your data when you release it so people know the period it relates to and when it will expire. | 
... | ...

Or with 1. and 2.

Basics | Field | Question | 
:--------- | ---- | --------- | 
General | Data Title | What's this data called? | 
General | Data Publisher | Who publishes this data? |
... | ... | ...
Social - Documentation | Code Lists | Are there any codes used in this data? |
**Pilot** | **Field** | **Question** | 
Practical - Accuracy | Timestamped | You should put timestamps in your data when you release it so people know the period it relates to and when it will expire. | 
... | ... | ...

**Comment by sumikasan** [comment]
I am closing this but will be re-visiting this feedback as part of the big UI review project for the certificates.
