### ISSUE TITLE
"Yes I understand" button doesn't work

### ISSUE THREAD

**Issue by ldodds** [theodi/open-data-certificate#994]
Reviewing the suggested improvements for a certificate, if I click "Yes I understand, edit questionnaire" then nothing happens.

The button seems to be missing the required link, the href is for, e.g `##q_607255`

**Comment by pkqk** [comment]
This appears to still be an issue but it is intermittent.

**Comment by pkqk** [comment]
Found the problem, it currently only works for incomplete questionnaires, once it's reached a certificate level then it doesn't generate a link.

I think the logic behind it is that the answers shouldn't change once it's published but that's not what the code is doing.

  - [ ] make it check that questionnaire is published for switching between behaviour
  - [ ] when published, make it follow the copy questionnaire flow like it does from other actions.
