### ISSUE TITLE
Ask a Human - discussion page hangs

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#996]
I tried to Ask a Human about the Right Statement question. When I press Submit, the page hangs.

![askahumanhangs](https://cloud.githubusercontent.com/assets/9379524/5407629/60b94158-8216-11e4-9eb8-07eebd34a482.PNG)

I tried a couple of times using a Chrome browser but got the same results each time.

The survey asks "Give the URL to a page that describes the right to re-use this dataset. This should include a reference to its license, attribution requirements, and a statement about relevant copyright. A rights statement helps people understand what they can and can't do with the data."

My question: Do I need to follow the [ODI Publisher's Guide to the Open Data Rights Statement Vocabulary] (http://opendatainstitute.org/guides/publishers-guide-to-the-open-data-rights-statement-vocabulary)? Can I just use DCAT terms and still get a Pilot certificate?

**Comment by pkqk** [comment]
fixed by https://github.com/theodi/juvia/commit/b65b38d0b6f3fdecb9721be3b499cc40f8746a27
