### ISSUE TITLE
Implementation Support

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/open-data-certificate#998]
I’m sorry if this is not the appropriate place to post this sort of question but the moderation on the [discussion forum](https://certificates.theodi.org/discussion) is slow and responses slower. 

I have found that our [CKAN portal](https://data.qld.gov.au) is not configured appropriately to automatically generate answers to the survey questions. Some guidance on which [CKAN extensions](http://extensions.ckan.org) to include to maximise automation and the certificate level achieved would be appreciated. 

The leader of our Open Data Initiative wants to create a policy that will apply to all Queensland Government datasets requiring:
* a minimum Raw certificate
* a target % of datasets by a date attaining a Pilot certificate (the % increasing over time)
* mandatory Pilot certificates for high value dataset with Standard certificates being desirable.
* Standard certificates for very high value datasets.

They have asked, "what is the effort for each department to comply with the policy?" before the policy is finalised.

Is the ODI or Open Knowledge (for CKAN-ODI certificate configuration) ready to provide consulting services or guides on this, or is it too early for that?

Is this github the best place to hold discussions about implementation issues?

Thanks 
Stephen Gates 
Stephen.Z.Gates@tmr.qld.gov.au

**Comment by pkqk** [comment]
Requires #1186 for basic list of questions.

@shevski has mentioned that an example data model for CKAN would be helpful

**Comment by shevski** [comment]
Currently improving the certificate ckan plugin / import to help fill out more of the certificate automatically, which should be finished in July!

#1186 will allow the next stage to build a metadata model that captures all the necessary info
